### PR TITLE
	Adding initial implementation of Slider (only mouse events for now)

### PR DESCRIPTION
**Pull request by devnook**

### CODE REVIEW

**Comment by jakearchibald** [comment]
Been playing around with styling ranges, it's horrible. I'd avoid it.

I'm experimenting with this strategy:

1. Take existing `<input type="range">`
2. Wrap it in a `<label>`
3. Put the fake slider in the label
4. Move the real range out of view

Now, when you click the fake slider, it focuses the real one. As long as you update the fake slider when the real one updates, voila, you have platform-natural keyboard events and focusing.

**Comment by jakearchibald** [comment]
Or better still, overlay the real slider over the top of the fake one, give it `opacity:0` and clickjack it.

**Comment by sgomes** [comment]
Well, our current approach seems to work reasonably well, even if it's essentially three implementations: one for webkit/blink, one for moz, and one for ms. There's a few issues with animations in some of them, but other than that it's working fine.

Thanks for the tip, though; I may reconsider that at some point, since we're already running js on change anyway.

**Comment by jakearchibald** [comment]
@sgomes where's the final implementation?

**Comment by sgomes** [comment]
The code is in the material-sprint branch: https://github.com/google/web-starter-kit/tree/material-sprint/app/styleguide/slider

We don't really have an updated version hosted anywhere atm, I'm afraid :-/

**Pull request closed without merging**
