### PR TITLE
Update to components with font-face so you can see headings in style …

### PR DESCRIPTION
**Pull request by brianmontanaweb**
Update to typography components with font-face so you can see headings in style guide for IE9+.

Removal of flex for .primary-content broken in IE11.

### CODE REVIEW

**Comment by brianmontana** [comment]
The compiled component.css didn't include a reference to Roboto, so added that and shows up in all supported browsers now. Flex is having issues in primary content, removed it so it's no longer overlapping in IE9+. Lemme know if you need more info.

**Comment by boucains** [comment]
Hi Brian - would it be appropriate to add single quote marks around the URL entries you changed? For example, I would use url('../fonts/fontname');. If this isn't appropriate, could you tel this noob why?

Thanks for making your change!

**Comment by brianmontanaweb** [comment]
It's optional to do quotes in url, so I don't include it. If it's not required I'll exclude it from the code.

**Comment by brianmontanaweb** [comment]
I signed it!

**Comment by boucains** [comment]
Hi Brian, 

Good reason. I have another question, however. SCSS LINT throws an error if the single quotes are omitted. Even if they are not technically required, if they are included they make LINTing a file easier.

Is this possibly a valid reason to include them?

Thanks!

**Comment by Garbee** [comment]
@boucains Your tooling should have some configuration to change that. Defaults are just for guidance and/or personal opinions of the main developers.

The styleguide here is deprecated anyways. [Material Design Lite](https://github.com/google/material-design-lite) has launched which replaces it.

**Comment by boucains** [comment]
@garbee Thanks! However, I'm a bit confused. SCSS LINT doesn't say this is optional. If I remove those quotes in my file, the styleguide loses those fonts. I'm certainly not going to tell @brianmontanaweb he's wrong. I'm sure that the fixes he instituted work on his system. All I can do is go by the results I get on my system. For that matter, the fixes provided by Brian don't include a ".." before the first slash. Again, on my system, if I don't include them, the styleguide can't find the font.

I hope you can see why this is confusing to me. This is something that I've seen over the last two years in several projects.  Any time you have to explain would be greatly appreciated. 

Also, thanks for the info on the depreciated style guide. Again, I'm confused. If it's deprecated, why is it still part of the project? Is this entire project out of date, and I should be looking at a different repo? If it's out of date, how would I know that unless I keep up on all the Google news?

Unless you're already part of a team of experienced people, trying to get involved or learn how to do some of this stuff is next to impossible.

**Comment by Garbee** [comment]
This repo is out of date. We are focusing on fixing up MDL a bit more before updating this to use it as far as I know.

Keeping up is difficult, but that is part of the job.

On getting support, with things like quoting, you should go to [StackOverflow](https://stackoverflow.com). There are many more developers there who are active on helping people. Along with probably the same things you are asking already answered a few times.

**Comment by brianmontanaweb** [comment]
@Garbee Thanks for helping @boucains :)

**Comment by nicolasgarnier** [comment]
Thanks for contributing @brianmontanaweb! I'm going to close this since we are now using [Material Design Lite](https://github.com/google/material-design-lite/) for components styling and typography. Feel free to have a look at [Material Design Lite](https://github.com/google/material-design-lite/) and contribute there if you think things can get improved there.

Cheers!

**Pull request closed without merging**
