### PR TITLE
Properly return the streams from our tasks.

### PR DESCRIPTION
**Pull request by mikelambert**
Otherwise bad things can happen, as in:

https://github.com/adametry/gulp-eslint/issues/36

### CODE REVIEW

**Comment by mikelambert** [comment]
I signed it!

**Comment by surma** [comment]
Yeah, def. good catch. Thank you, @mikelambert  :)

**Comment by a-magdy** [comment]
Hi,

This crashed when I ran it locally.

SyntaxError ... Unexpected Token => at the "return gulp..."

After removing all the returns, it is working fine now.

Are you sure that the return is correct here !

**Comment by surma** [comment]
I genuinely ran the code but apparently forgot to reset to `master`. Reverted in 34cad76.

It was also a mistake in the first place by me to merge it, as fat arrow function implicitly return the value.

Thanks for checking, @a-magdy. Saved me here :wink:

**Comment by mikelambert** [comment]
Ugh sorry, I was totally unaware of any difference between x => { ... } and x => ... !

I had grabbed some of this code for inclusion in my own project, and I guess I had accidentally {}-ified it in the process for some reason, and took me a bit of sleuthing to figure out why it wasn't working for me, and mistakenly thought I should contribute the fixes back.

Thanks for the quick reversion!

**Comment by surma** [comment]
No worries. Chain of unfortunate mistakes ^^

**Pull request merged**
