### PR TITLE
Making sure gulp-newer does not filter out SCSS files.

### LINKED ISSUE #326: editing scss files doesn't seem to update styles on page
hello all, not sure if it's me missing something or what, but I have cloned the repo and run 'npm install' from the directory with no issues. However, once running 'gulp serve', when I go to change any scss files gulp seems to run the 'styles' job like it should and the page reloads, but none of the styles change. The gulp file seems to update the '.tmp/styles/*' files correctly, but the reload doesn't then use these files.

Simple example, deleting the entire contents of the 'app/styles/components/components.scss' file and saving seems to run all the gulp tasks and reloads the browser, but all styling stays the same.

Any help would be much appreciated, I'm sure it's something I am doing stupidly wrong.

Many thanks in advance.
Mat

### PR DESCRIPTION
**Pull request by nicolasgarnier**
Fixes #326 
@addyosmani PTAL

### CODE REVIEW

**Comment by robwierzbowski** [comment]
You could also place the newer task after the `sass` task, which IMO makes the intent of running Sass on all files every time a little more clear. 

It looks like the node/libsass maintainer's official position is it's so fast it doesn't need caching: https://github.com/sass/node-sass/issues/246#issuecomment-127585961

**Comment by robwierzbowski** [comment]
An example of my suggestion above:

```js
gulp.task('styles', () => {
  const SUPPORTED_BROWSERS = ['last 2 versions', '> 5%'];

  return gulp.src('app/styles/main.scss')
  .pipe($.sourcemaps.init())
  .pipe($.sass({
    precision: 10
  }).on('error', $.sass.logError))
  .pipe($.changed('.tmp/styles', {hasChanged: $.changed.compareSha1Digest}))
  .pipe($.autoprefixer(SUPPORTED_BROWSERS))
  .pipe($.sourcemaps.write())
  .pipe(gulp.dest('.tmp/styles'));
});
```

**Comment by addyosmani** [comment]
@robwierzbowski would you mind opening a new issue with your suggestions so we can walk through them in more detail? Atm, I'm going to land the current patch as it's better than what we have in place today but am very interested in making the intent of steps used more clear.

**Comment by robwierzbowski** [comment]
Sure. It's not a big deal, just a possible refinement.

On Thursday, October 1, 2015, Addy Osmani <notifications@github.com> wrote:

> Merged #749 <https://github.com/google/web-starter-kit/pull/749>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/web-starter-kit/pull/749#event-424330277>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Pull request merged**
