### PR TITLE
bump deps: gulp-sass@1.3.3 works on node 0.12 and io.js

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by stevemao** [comment]
Weird. I thought gulp-sass@1.3.3 worked with io.js https://github.com/dlmanning/gulp-sass/commit/314ce5c1594e541a55e5c5009fb0733c45226567

I'll just do version bump then.

**Comment by addyosmani** [comment]
Thanks for the PR @stevemao. The change itself looks fine but we'll need to do more extensive testing before making the deps switch. We'll try to do this soon (cc @sgomes @gauntface).

**Comment by addyosmani** [comment]
@stevemao want to rebase this against master?

**Comment by stevemao** [comment]
Sure thing

**Comment by stevemao** [comment]
Done

**Comment by addyosmani** [comment]
Hmm. This is failing in our Travis builds atm even with failures allowed in https://github.com/google/web-starter-kit/blob/master/.travis.yml. @sindresorhus is that expected?

**Comment by stevemao** [comment]
Looks like it's node-sass again :angry:

**Comment by stevemao** [comment]
Travis is not failing now :smile:

**Comment by addyosmani** [comment]
Hah. Awesome. Let's keep this open a short while so we can get some further testing done, but the change otherwise lgtm.

**Comment by addyosmani** [comment]
@nicolasgarnier is this change still necessary?

**Comment by nicolasgarnier** [comment]
Yes!. Would be nice to get this in.

@stevemao could you rebase please?

**Comment by stevemao** [comment]
Done.

**Comment by sindresorhus** [comment]
Closing as this PR is now moot.

**Pull request closed without merging**
