### PR TITLE
Fix gulpfile to follow project's jscs rules

### PR DESCRIPTION
**Pull request by theponti**
Fix space between `function` keyword and `()` which were breaking the project's `.jscsrc` rules

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's the .jscsrc that is wrong. Happy to receive a PR for that though ;)

**Comment by jacquerie** [comment]
I might be wrong, but there's not way to submit a PR to fix the `.jscsrc`. In fact, having no space between the `function` keyword and the opening round bracket is enforced by the `google` preset: https://github.com/jscs-dev/node-jscs/blob/8bd2ffd7bd1fc53a49d017f06322b178124534fa/presets/google.json#L54, and the `.jscsrc` can't override that.

**Comment by sindresorhus** [comment]
@jacquerie You can override preset rules.

**Comment by jacquerie** [comment]
Whoops, you're right. I was trying to set it to `false` instead of `null`.

**Pull request closed without merging**
