### PR TITLE
Add support for Service Worker to master

### PR DESCRIPTION
**Pull request by addyosmani**
This PR lands the support for Service Worker we added to material-sprint to master. 

I'll be incrementally bringing features in on top of what we have now to cleanly separate what is still useful to WSK vs. the Material Design library.

r: @passy @sindresorhus

### CODE REVIEW

**Comment by passy** [comment]
Looks good at a quick glance, will do some testing in the next days. Thanks, Addy!

**Comment by addyosmani** [comment]
Thanks for taking a look!

**Comment by addyosmani** [comment]
cc @surma too in case you're interested in trying this out.

**Comment by passy** [comment]
:+1: Works great for me.
screenshot 2015-04-20 18 11 57

**Comment by addyosmani** [comment]
Fantastic. Thanks for taking the time to review :heart:

**Pull request merged**
