### PR TITLE
Update year

### PR DESCRIPTION
**Pull request by rafaelstz**

### CODE REVIEW

**Comment by rafaelstz** [comment]
I signed it!

**Comment by Garbee** [comment]
We should probably get some legal consult here... I'm not sure if we should ever remove a copyright year. There is some discussion on [SO](http://stackoverflow.com/a/3487026/2604748) about it which shows it may not be a good idea. If anything, the current year should be appended but not overwriting.

**Comment by rafaelstz** [comment]
Done :+1:  @Garbee

**Comment by addyosmani** [comment]
LGTM. Thanks for the comments (which are correct legally speaking) @Garbee!

**Pull request merged**
