### PR TITLE
ES2015ify the gulpfile

### PR DESCRIPTION
**Pull request by sindresorhus**
Gulp 3.9, which was just released, got support for transpiling using Babel, and Babel is pretty stable.

I think now is a good time to embrace ES2015.

-

*It's two commits for diff purposes. Will squash before merge.*

-

//@addyosmani @sebmck @thejameskyle

### CODE REVIEW

**Comment by sebmck** [comment]
:heart_eyes:

**Comment by arthurvr** [comment]
:heart:

**Comment by thejameskyle** [comment]
:+

**Comment by addyosmani** [comment]
LGTM. Landed via 9bfe849535ad2d5b474198f7f6544c96934e375e

**Comment by arthurvr** [comment]
@addyosmani Is this something we should consider doing at PSK? I know Polymer doesn't acutally want to use ES6 for the source files, but I wonder if it makes sense for the gulpfile?

**Comment by addyosmani** [comment]
@arthurvr For now I'd like to keep the gulpfile setup in PSK as is and bring in ES6 changes to it with the rest of the codebase when we're ready. It'll be worth keeping an eye on our users reactions to the Babel changes here too in case there are lessons go be learned beforehand :)

**Comment by thejameskyle** [comment]
Let us know if users have any issues!

**Pull request closed without merging**
