### PR TITLE
Replace deprecated minifiers with gulp-cssnano and gulp-htmlmin

### LINKED ISSUE #802: Replace gulp-minify-html with gulp-htmlmin
Gulp plugin `gulp-minify-html` got [deprecated](https://github.com/murphydanger/gulp-minify-html/commit/c9e992c36cb528816341cb675f360c1865723d78). Probably, it worth now to switch to recommended [gulp-htmlmin](https://github.com/jonschlinkert/gulp-htmlmin)?

### PR DESCRIPTION
**Pull request by robwierzbowski**
Fixes #802.

Replaces deprecated minify-html and minify-css plugins with recommended plugins htmlmin and cssnano.

gulp-htmlmin currently has to be manually configured; there are no sensible defaults. These transforms are all relatively safe, and in my experience provide the bulk of HTML minification gains, but I'm open to any changes.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR, @robwierzbowski! I was planning on getting this updated but got swamped. Really appreciate you writing the patch.

**Comment by addyosmani** [comment]
LGTM

**Comment by addyosmani** [comment]
@robwierzbowski btw, interested in helping us maintain the repo? You've been great at helping out with PRs for quite some time and I think we should just give you committer rights if you're interested.

**Comment by robwierzbowski** [comment]
@addyosmani That would be great :D. 

At some point in the near future I'm going to move one of my projects to gulp 4. If it works out maybe I'll give converting WSK a try.

**Comment by addyosmani** [comment]
@robwierzbowski We're planning on moving everything to Gulp 4 soooon :) @gauntface and @surma are taking a look at that over in https://github.com/google/web-starter-kit/tree/wsk2

**Comment by addyosmani** [comment]
@robwierzbowski you should have commit rights now :zap:

**Comment by robwierzbowski** [comment]
Awesome!

Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by surma** [comment]
@robwierzbowski You may want to take a look at the super secret `wsk2` branch and `towards-wsk2` label, that @gauntface and I are working on right now. Gulp 4 is on its way :tada:

**Comment by robwierzbowski** [comment]
@surma Yeah, I poked around a little. Looks great, looking forward to contributing to it soon!

**Pull request merged**
