### PR TITLE
Remove unused gulp-flatten and gulp-replace plugins

### PR DESCRIPTION
**Pull request by robwierzbowski**
Correct me if I'm wrong, but gulp-flatten and gulp-replace don't seem to be used anywhere in WSK. A git grep of the project seems to confirm.

### CODE REVIEW

**Comment by robwierzbowski** [comment]
I believe I've signed the CLA before for Yeoman contributions.

Also, seems like gulp-replace isn't used...

**Comment by addyosmani** [comment]
Thanks @robwierzbowski. Reviewing the current gulpfile, which has been through a few different sets of refactors I wasn't able to find a place where either of these are being used directly either. @nicolasgarnier could you help us do one more sweep before we land this change?

**Comment by arthurvr** [comment]
This should be all right. I did the same in PSK a while ago: https://github.com/PolymerElements/polymer-starter-kit/commit/74221ae6fc6f4d45aab8d7c38b54f2d96bd4ceef.

**Comment by addyosmani** [comment]
Let's merge away. Verified this shouldn't be an issue. Thanks for the check in @arthurvr! Always appreciated :)

**Pull request merged**
