### PR TITLE
Switching gulp-changed to gulp-newer.

### LINKED ISSUE #326: editing scss files doesn't seem to update styles on page
hello all, not sure if it's me missing something or what, but I have cloned the repo and run 'npm install' from the directory with no issues. However, once running 'gulp serve', when I go to change any scss files gulp seems to run the 'styles' job like it should and the page reloads, but none of the styles change. The gulp file seems to update the '.tmp/styles/*' files correctly, but the reload doesn't then use these files.

Simple example, deleting the entire contents of the 'app/styles/components/components.scss' file and saving seems to run all the gulp tasks and reloads the browser, but all styling stays the same.

Any help would be much appreciated, I'm sure it's something I am doing stupidly wrong.

Many thanks in advance.
Mat

### PR DESCRIPTION
**Pull request by nicolasgarnier**
Fixes #326 

@addyosmani PTAL?

### CODE REVIEW

**Comment by addyosmani** [comment]
Is there an upstream issue with `gulp-changed` about the problems we ran into with many:1 file transformation support? Would be useful to cross-reference. @sindresorhus is usually pretty responsive :)

**Comment by sindresorhus** [comment]
`gulp-changed` is not going to support many:1, so best to switch to `gulp-newer`.

**Comment by addyosmani** [comment]
SGTM. Thanks for the input :star2:

**Comment by addyosmani** [comment]
Changes LGTM.

**Pull request merged**
