### PR TITLE
sw-precache 2.2.0

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani 

Updates to match the new interface exposed in sw-precache 2.2.0. There are also some tweaks to the registration process to match the current best practices.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks @jeffposnick. That was fast :) I'll test these changes locally. They otherwise initially LGTM. Appreciate the PR!

**Comment by addyosmani** [comment]
When testing your PR with these changes (against a clean profile with SW caches emptied and SWs unregistered), I'm unable to get this working offline. Tested using DevTools network throttling + just switching off wifi.

Is this possibly related to https://github.com/google/web-starter-kit/pull/768, or are you able to get everything working offline on your end?

**Comment by sindresorhus** [comment]
:+1: Haven't tested this, but Iike the new simplified API :)

**Comment by jeffposnick** [comment]
Are you testing `serve` or `serve:dist`?

`serve` uses a no-op `service-worker.js`, and it won't work offline. Using the `sw-precache`-generated `service-worker.js` makes it very difficult to quickly test local changes (you'd end up reloading multiple times, or need to use an incognito window), so it's not really appropriate for a development server environment.

`serve:dist` uses the `sw-precache`-generated output, and should work offline. #768 is related, yes, to ensure that the no-op and functional SWs don't mingle unexpectedly

I should make this explicit in the docs, and can do that in a follow-up PR if you can confirm that `serve:dist` works as expected.

**Comment by jeffposnick** [comment]
(Credit goes to @callumlocke for making the methods play nicely with promises in addition to callbacks.)

**Comment by addyosmani** [comment]
This was testing using both `serve` and `serve:dist`. I'll nix my local dependency setup and retry just in case.

**Comment by addyosmani** [comment]
Re-tested. We are in fact working correctly now on `serve:dist` (thanks, Jeff!). The other caching issue I'm running into is to do with changes we made to WSK around our use of MDL.

We currently use the following CDN files, which are not being cached and result in an unstyled page being loaded from the SW cache:

* https://storage.googleapis.com/code.getmdl.io/1.0.2/material.indigo-pink.min.css 
* https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js
* https://fonts.googleapis.com/icon?family=Material+Icons 

We may need to think about how we handle caching for these files and whether we need to worry about falling back to local files instead.

**Comment by jeffposnick** [comment]
I didn't realize that there were now some remote dependencies.

The SW that `sw-precache` generates only handles local static dependencies via a cache-first strategy. When there are remote or dynamic resources, what I would normally do is use [`importScripts`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring) to pull in the `sw-toolbox` library and set that up to handle the caching with an appropriate strategy.

It's probably cleanest to handle that in a different PR, and treat this one just for the update to the `sw-precache` interface.

**Comment by addyosmani** [comment]
It's entirely my fault as I should have mentioned that earlier. I agree that it would be clean to handle using `importScripts` for our CDN deps in follow-up PR. As this is otherwise working, LGTM for landing.

Thanks @jeffposnick!

**Pull request merged**
