### PR TITLE
Switch main.scss -> main.css

### PR DESCRIPTION
**Pull request by addyosmani**
This is a minor change, but enables a user to `cd app` and then run any server (without needing to `npm install` anything) to play around with Web Starter Kit. 

Simply renaming the file back to main.scss or dropping in other .scss files will still work fine in the `styles` directory, but figured this was worth making a change for.

r: @sindresorhus or @passy

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1:

**Comment by passy** [comment]
Cool! :+1:

**Comment by addyosmani** [comment]
Thanks fellas!

**Pull request merged**
