### PR TITLE
Changing Bullet to Horizontal Line

### PR DESCRIPTION
**Pull request by imkarthikk**
The dot bothered me so much. So changing it to a line rather than a bullet point.

### CODE REVIEW

**Comment by imkarthikk** [comment]
I signed it!

**Review by gauntface — APPROVED** [review]
Thank you

**Comment by Montesdodgers13** [comment]
---------- Forwarded message ----------
From: <notifications@mail.status.python.org>
Date: Saturday, March 10, 2018
Subject: [Python Infrastructure status] Update : PyPI Maintenance
To: raiders13@calebvalle.com


PyPI Maintenance <http://stspg.io/18c033eb5>
Incident Report for Python Infrastructure
An Incident Update Has Been Posted
We've completed the first of two migrations. The second should complete in
the next 5 minutes and we'll be back online if all goes well.
Mar 10, 14:21 UTC
Previous Updates
Monitoring
PyPI requires a database migration that necessitates an exclusive lock on a
busy table.

In order to perform this we're going to temporarily place PyPI into
maintenance mode.
Mar 10, 14:06 UTC
This incident affects: pypi.python.org.
View status page <https://status.python.org> or manage your subscription
<https://status.python.org/manage/2l3dptn5rjrk> to these emails.
Powered by Statuspage
<https://www.statuspage.io/?utm_source=inapp&utm_medium=powered-by&utm_campaign=status.python.org&utm_content=email-notifications>



--

**Pull request merged**
