### PR TITLE
code styling fix on issue #500

### PR DESCRIPTION
**Pull request by codeandrop**
Hi @addyosmani and @jasonmayes, here are the fixes for the h2 and white-spaces.

I left lang attribute as is.

Let me know if it's ok to merge.

### CODE REVIEW

**Comment by codeandrop** [comment]
@googlebot I did author this commit, I know you are a bot, but just to ACK :)

**Comment by addyosmani** [comment]
@sgomes LGTY?

**Comment by sgomes** [comment]
@addyosmani LGTM, merging. Thanks, @codeandrop!

**Comment by codeandrop** [comment]
@sgomes glad I can help! I'm so happy since this is my first PR to a google project :smiley:

**Pull request merged**
