### PR TITLE
Fixes #597: Add useref css block back to index.html

### LINKED ISSUE #597: No useref css build block in index.html
There's no useref css build block in index.html by default so uncss is not used. Is it intentional? I can send a PR if it's a bug

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by stevemao** [comment]
Any problem with this PR?

**Comment by addyosmani** [comment]
Gotcha. We've been redoing how this works over in material-sprint-branch. I need to bring the core build changes back into master as I think the overall workflow is a little cleaner.

**Comment by stevemao** [comment]
Thanks @addyosmani , looks like material-sprint-branch is also using useref at the moment. I'm excited to see a completely new workflow soon :smile:

**Comment by stevemao** [comment]
@addyosmani So you just want useref to swap out all the reference rather than using it in the workflow? If so I can do a PR. I just did some researches and there is no need to do https://github.com/google/web-starter-kit/commit/7209260cc099fac7eb6910002985bcc0f46126bf.

**Comment by stevemao** [comment]
Also I can solve all the issues I raised here about useref if this is the case.

**Comment by stevemao** [comment]
#597

**Pull request closed without merging**
