### PR TITLE
Service-worker based caching using sw-precache

### PR DESCRIPTION
**Pull request by jeffposnick**
@PaulKinlan @addyosmani & co.:

As discussed in #606, here's an approach to adding in offline support to WSK using the `sw-precache` module.

### CODE REVIEW

**Comment by addyosmani** [comment]
Verified as working correctly both in Device Mode while offline and actually offline:

**Comment by addyosmani** [comment]
Tech review complete. Minor nits:

* Can we limit the code-width for comments to 80 characters?
* Remove the Style Guide from the glob patterns list in `staticFileGlobs`
* `dynamicUrlToDependencies` should have a one-line comment summarising https://github.com/jeffposnick/sw-precache#dynamicurltodependencies-objectstringarraystring. It's unclear to me atm whether I need to change this should I wish to support multiple markup files.
* Please add a one-line comment for `stripPrefix` summarising https://github.com/jeffposnick/sw-precache#stripprefix-string

**Comment by addyosmani** [comment]
Open question: Beginners and intermediate users are unlikely to have an SSL/HTTPs enabled web server. While Service Worker will work fine for them offline given localhost is whitelisted, they may be surprised to find this doesn't work in production.

What can we do to alleviate this? Some options:

* Include a comment reiterating the HTTPs requirement for this section
* Comment out Service Worker configuration. User must uncomment to use/enable.
* Don't include sw-precache in the default Gulpfile, but instead author a recipe for the `docs` directory which walks users through adding this in. Such a guide could also link up to additional SW resources.

Looping in @gauntface @paullewis @passy @sindresorhus for their thoughts.

**Comment by passy** [comment]
> Include a comment reiterating the HTTPs requirement for this section

Advocating for HTTPS might be a good thing regardless of whether SW is enabled or not. As it gets easier and cheaper to deploy (gh-pages, Heroku, Cloudflare Universal SSL and EFF's Let's Encrypt) it should definitely not prevent anyone from using this.

And on a more general note, I'm really excited about including this with WSK and getting some ServiceWorker code into hundreds (if not more) pages that would otherwise probably never see it.

**Comment by sindresorhus** [comment]
> Advocating for HTTPS might be a good thing regardless of whether SW is enabled or not. As it gets easier and cheaper to deploy (gh-pages, Heroku, Cloudflare Universal SSL and EFF's Let's Encrypt) it should definitely not prevent anyone from using this.

:+1: Is there like a "the ultimate SSL guide" we could link to?

**Comment by addyosmani** [comment]
> Is there like a "the ultimate SSL guide" we could link to?

https://twitter.com/fugueish/status/548589307502395392 maybe? I've asked Chris to consider publishing this on Web Fundamentals or Chromium.org.

**Comment by addyosmani** [comment]
FYI, Jeff has started work on addressing some of @PaulKinlan's feedback on the getting started experience for WSK + Service Workers over in #617.

**Comment by jeffposnick** [comment]
I just pushed some updates to address https://github.com/google/web-starter-kit/pull/613#issuecomment-71447663. It was hard to stick to one line for some of the comments, though.

I also put in a default value for the `cacheId` based on `package.json`'s `name`, assuming it's set.

(I'm fairly sure that `sw-precache` will help with the pain point @PaulKinlan details in https://github.com/google/web-starter-kit/issues/617, but we can continue that conversation there.)

**Comment by addyosmani** [comment]
Thank you for updating, @jeffposnick! Changes LGTM. It primarily looks like the the lines that are still > 80 are long URLs, so let's keep them as is for now. Can we get these commits squashed in preparation to land? :)

Testing SW when served over a non-secure origin with SW caching in place, the user may see "Mixed content" warnings in DevTools, saying that the content must be loaded over HTTPs in order to correctly load from cache. 

Given the average end-user is unlikely to have DevTools open, but a developer will, I'm personally okay with this. Does anyone have any concerns here before we land this set of changes?

**Comment by passy** [comment]
Tested in latest Canary and works wonderfully. I'm happy with it! :) :+1:

**Comment by jeffposnick** [comment]
My `rebase`-fu is weak, but I think the squash worked.

Based on the comment around logging noise in https://github.com/google/web-starter-kit/pull/613#issuecomment-72024509, [I added in a check](https://github.com/jeffposnick/web-starter-kit/blob/material-sprint/app/scripts/main.js#L27) to ensure we're on a [secure origin](http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features) before attempting SW registration. It means that on non-secure origins, there won't be any console feedback about the lack of SW support, but it is friendlier for actual deployments.

**Comment by addyosmani** [comment]
Changes LGTM. Thanks so much for working on this, @jeffposnick! :star:

**Comment by jeffposnick** [comment]
:fireworks:

**Pull request merged**
