### PR TITLE
Add CDNJS badge in readme

### PR DESCRIPTION
**Pull request by kennynaoh**
This will add the badge to show its version on CDNJS and also link to its page on CDNJS!

### CODE REVIEW

**Comment by kennynaoh** [comment]
I signed it!

**Comment by Garbee** [comment]
This should not be on CDNJS. It is an application quick-start not a library to include at-will within your other projects.

**Comment by kennynaoh** [comment]
Actually, it is already on CDNJS https://cdnjs.com/libraries/web-starter-kit. We still can include it through CDNJS.

**Comment by Garbee** [comment]
Whether it is already there or not is hardly relevant. Having a badge on the project encourages its use. Which we shouldn't since that is not the way the repo is meant to be used/distributed.

It is about keeping usage clear to our end-users who are already confused about what tools apply where and in what context. This just muddies things even further and for something that is clearly an incorrect thing to be distributed using something like CDNJS. We're an application starter repo, not a library to be included at-will.

I understand someone may have added it to CDNJS without understanding the consequences it could have on developers. However, that doesn't mean the project should add a badge supporting that context.

**Comment by kennynaoh** [comment]
Thank you for your explanation. I got it.

**Pull request closed without merging**
