### PR TITLE
don't allow failures anymore

### PR DESCRIPTION
**Pull request by bUUnOpp**
allowing something to break is bad

### CODE REVIEW

**Comment by bUUnOpp** [comment]
I don't sign anything.

**Comment by addyosmani** [comment]
This was an intentional change in our Travis setup. Closing.

**Comment by bUUnOpp** [comment]
It was intentional as it was for node-sass on io.js.Those issues are fixed now. Please discuss something before closing the ticket :)

**Comment by Garbee** [comment]
It still would end up being closed since you are not willing to sign the CLA. This is required for anyone contributing to a Google Open Source project. Without a signed CLA, no contribution can be accepted.

**Pull request closed without merging**
