### PR TITLE
upgrade to mdl 1.1.3 and change locations as well

### PR DESCRIPTION
**Pull request by akkumar**
Change the path of mdl libraries as per the getting started guide here - https://getmdl.io/started/ .

### CODE REVIEW

**Comment by Garbee** [comment]
LGTM

**Comment by akkumar** [comment]
I signed it!

**Comment by addyosmani** [comment]
LGTM2. Thanks!

**Comment by akkumar** [comment]
Thanks @addyosmani , @Garbee  . It would be a nice-to-have a 0.6.5 release with this version upgrade / location change though. FYI .

**Comment by Garbee** [comment]
Nah, 1.0.3 has a major bug. We are about to push 1.0.4. So when that gets put here we'll slice a new release.

**Comment by addyosmani** [comment]
SGTM

**Pull request merged**
