### PR TITLE
Add tasks for static assets revisioning

### PR DESCRIPTION
**Pull request by srus**
Static assets revisioning in production built, in order to flush client cache whenever files change.

### CODE REVIEW

**Comment by addyosmani** [comment]
I'm :-1: on static asset revisioning based on our experiences with using it in Yeoman. @sindresorhus any thoughts?

**Comment by sindresorhus** [comment]
Same :-1:. I only have bad experience with revving and it's a nightmare to maintain as it complicates everything and creates so many edge-cases. If this lands the support requests will increase dramatically.

**Comment by Garbee** [comment]
:-1: as well here. Developers can decide how best to revision their assets for their use-cases. Sometimes this may not even be necessary.

**Comment by addyosmani** [comment]
With 3 votes from the team, closing this.

**Comment by srus** [comment]
I agree that it would increase support requests...   so it's ok :)

**Pull request closed without merging**
